spring:
  datasource:
    url: jdbc:mysql://211.38.86.92:3306/lier?serverTimezone=UTC&characterEncoding=UTF-8
    username: outuser
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
server:
  port: 8010
